### ISSUE TITLE
Week 12 Meetings 

### ISSUE THREAD

**Issue by rickyyx** [githubxxcc/ParNVM#10]
## TODO
- [x] One thread (without any dependency tracking) throughput 
- [x] Use Per thread Tid allocation 
- [x] Use R/W Spin locks 
- [x] Move key sorting out of the transaction 

- [ ] More buckets 
- [ ] OCC scaling with no conflicts graph
