### ISSUE TITLE
How to enforce correct runtime execution? 

### ISSUE THREAD

**Issue by rickyyx** [githubxxcc/ParNVM#5]
For each transaction worker:
- init with a list of pieces and the conflict graph
- get the next runnable piece
- run the piece (potential race?) 

#### How does a worker get the workload?
- The chopper(test chopper) should register the workload
- Each worker will then get a list of transactions consisting of pieces
- Each worker will also get part of the conflict graph. 

#### How to find out if a piece is runnable? 
- Global data structure keeps track of what transaction programs are being run by which transaction instances and transaction worker. (Tid)
- Check the progress of that transaction worker, ($
  - by checking the log? (presence of log means the piece has already started) 
  - by checking some bits? 
- Cannot run if there are existing dependencies conflicting pieces($dep list)  that have not run => delay 

#### When running piece, what to update?
Dependency list:
- In the previous step, whenever found a transaction instance that has already ran a conflicting piece, add it into the $dep list

Progress :
- this has to be in sync with the progress checking. 

 

### TODO:
- [x] Implement hard-coded chopped pieces and conflict graph. 
- [x] Implement transaction worker. 
- [x] multiple txn instances of the same transaction base need to handle conflicts of itself. 
- [ ] insertions, how to lock it and do persistence?
